from __future__ import annotations

from dataclasses import dataclass

from .models import Axis


@dataclass(frozen=True)
class MetricSpec:
    code: str
    label: str
    unit: str
    direction: str
    weight: float
    raw_min: float
    raw_max: float
    source_id: str
    source_name: str
    endpoint: str
    source_url: str
    reference_date: str
    note: str | None = None


METRIC_CATALOG: dict[Axis, tuple[MetricSpec, ...]] = {
    Axis.CONVENIENCE: (
        MetricSpec(
            "station_density",
            "可住地面積あたり駅数",
            "駅/100km²",
            "higher_is_better",
            0.30,
            0,
            80,
            "MLIT-XKT015",
            "国土交通省 不動産情報ライブラリ",
            "XKT015",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt015/",
            "2023",
        ),
        MetricSpec(
            "railway_lines",
            "利用可能な鉄道路線数",
            "路線",
            "higher_is_better",
            0.20,
            0,
            12,
            "MLIT-XKT015",
            "国土交通省 不動産情報ライブラリ",
            "XKT015",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt015/",
            "2023",
        ),
        MetricSpec(
            "station_passengers",
            "駅乗降客数規模",
            "万人/日",
            "higher_is_better",
            0.20,
            0,
            80,
            "MLIT-XKT015",
            "国土交通省 不動産情報ライブラリ",
            "XKT015",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt015/",
            "2023",
        ),
        MetricSpec(
            "retail_density",
            "小売・サービス事業所密度",
            "事業所/千人",
            "higher_is_better",
            0.20,
            1,
            30,
            "ESTAT-0000020303",
            "e-Stat 社会・人口統計体系 C 経済基盤",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2023",
        ),
        MetricSpec(
            "daytime_population_ratio",
            "昼夜間人口比率",
            "%",
            "higher_is_better",
            0.10,
            60,
            180,
            "ESTAT-0000020301",
            "e-Stat 社会・人口統計体系 A 人口・世帯",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2020",
        ),
    ),
    Axis.HOUSING: (
        MetricSpec(
            "transaction_unit_price",
            "住宅取引単価中央値",
            "万円/㎡",
            "lower_is_better",
            0.50,
            5,
            140,
            "MLIT-XIT001",
            "国土交通省 不動産情報ライブラリ",
            "XIT001",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xit001/",
            "直近4四半期",
            "物件種別を分けて集計する前提",
        ),
        MetricSpec(
            "official_land_price",
            "住宅地の公示地価中央値",
            "万円/㎡",
            "lower_is_better",
            0.30,
            2,
            180,
            "MLIT-XPT002",
            "国土交通省 不動産情報ライブラリ",
            "XPT002",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xpt002/",
            "2025",
        ),
        MetricSpec(
            "housing_stock",
            "世帯あたり住宅ストック",
            "戸/千世帯",
            "higher_is_better",
            0.20,
            800,
            1400,
            "ESTAT-0000020308",
            "e-Stat 社会・人口統計体系 H 居住",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2023",
        ),
        MetricSpec(
            "residential_land_price",
            "住宅地の地価調査基準地中央値",
            "円/㎡",
            "lower_is_better",
            0.20,
            5_000,
            350_000,
            "MLIT-KSJ-L02-2026",
            "国土交通省 国土数値情報 都道府県地価調査",
            "L02-2026",
            "https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-L02-2026.html",
            "2026-07-01",
            "住宅地の基準地点中央値。家賃・売買成約価格ではない",
        ),
    ),
    Axis.FAMILY: (
        MetricSpec(
            "clinics_per_100k",
            "人口10万人あたり診療所数",
            "施設/10万人",
            "higher_is_better",
            0.30,
            20,
            180,
            "ESTAT-0000020309",
            "e-Stat 社会・人口統計体系 I 健康・医療",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2023",
        ),
        MetricSpec(
            "emergency_hospitals",
            "救急対応医療施設",
            "施設",
            "higher_is_better",
            0.20,
            0,
            20,
            "MLIT-XKT010",
            "国土交通省 不動産情報ライブラリ",
            "XKT010",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt010/",
            "公開データ基準年",
        ),
        MetricSpec(
            "nursery_per_1000_children",
            "子ども千人あたり保育・幼児教育施設",
            "施設/千人",
            "higher_is_better",
            0.30,
            1,
            35,
            "MLIT-XKT007",
            "国土交通省 不動産情報ライブラリ",
            "XKT007",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt007/",
            "公開データ基準年",
            "定員・空き状況は表さない",
        ),
        MetricSpec(
            "schools_per_1000_children",
            "子ども千人あたり学校数",
            "校/千人",
            "higher_is_better",
            0.20,
            0.5,
            15,
            "MLIT-XKT006",
            "国土交通省 不動産情報ライブラリ",
            "XKT006",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt006/",
            "公開データ基準年",
        ),
        MetricSpec(
            "tertiary_education_campuses",
            "大学・短大・高専の掲載キャンパス数",
            "キャンパス",
            "context_only",
            0.05,
            0,
            100,
            "MLIT-KSJ-P29-2023",
            "国土交通省 国土数値情報 学校",
            "P29-2023",
            "https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-P29-2023.html",
            "2023",
            "市内掲載キャンパス数のみ。稼働状況・定員・学部・通学時間は示さない",
        ),
    ),
    Axis.SAFETY: (
        MetricSpec(
            "crime_rate",
            "人口千人あたり刑法犯認知件数",
            "件/千人",
            "lower_is_better",
            0.25,
            1,
            25,
            "ESTAT-0000020311",
            "e-Stat 社会・人口統計体系 K 安全",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2023",
        ),
        MetricSpec(
            "traffic_accidents",
            "人口10万人あたり交通事故件数",
            "件/10万人",
            "lower_is_better",
            0.15,
            50,
            800,
            "ESTAT-0000020311",
            "e-Stat 社会・人口統計体系 K 安全",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2023",
        ),
        MetricSpec(
            "flood_exposure",
            "洪水浸水想定区域への曝露",
            "%",
            "lower_is_better",
            0.30,
            0,
            80,
            "MLIT-XKT026",
            "国土交通省 不動産情報ライブラリ",
            "XKT026",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt026/",
            "公開データ基準年",
            "市区町村境界との事前GIS集計を想定",
        ),
        MetricSpec(
            "landslide_exposure",
            "土砂災害警戒区域への曝露",
            "%",
            "lower_is_better",
            0.15,
            0,
            50,
            "MLIT-XKT029",
            "国土交通省 不動産情報ライブラリ",
            "XKT029",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt029/",
            "公開データ基準年",
        ),
        MetricSpec(
            "shelters_per_10k",
            "人口1万人あたり指定緊急避難場所",
            "施設/万人",
            "higher_is_better",
            0.15,
            0,
            30,
            "MLIT-XGT001",
            "国土交通省 不動産情報ライブラリ",
            "XGT001",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xgt001/",
            "公開データ基準年",
        ),
    ),
    Axis.FUTURE: (
        MetricSpec(
            "population_retention_2040",
            "2040年人口維持率",
            "%",
            "higher_is_better",
            0.35,
            35,
            130,
            "ESTAT-0000020301",
            "e-Stat 社会・人口統計体系 A 人口・世帯",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2040推計",
        ),
        MetricSpec(
            "population_retention_2050",
            "2050年人口維持率",
            "%",
            "higher_is_better",
            0.25,
            20,
            140,
            "ESTAT-0000020301",
            "e-Stat 社会・人口統計体系 A 人口・世帯",
            "getStatsData",
            "https://www.e-stat.go.jp/regional-statistics/ssdsview/",
            "2050推計",
        ),
        MetricSpec(
            "working_age_retention",
            "生産年齢人口維持率",
            "%",
            "higher_is_better",
            0.25,
            20,
            130,
            "MLIT-XKT013",
            "国土交通省 不動産情報ライブラリ",
            "XKT013",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt013/",
            "2050推計",
        ),
        MetricSpec(
            "child_population_retention",
            "年少人口維持率",
            "%",
            "higher_is_better",
            0.15,
            10,
            150,
            "MLIT-XKT013",
            "国土交通省 不動産情報ライブラリ",
            "XKT013",
            "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt013/",
            "2050推計",
        ),
    ),
}


AXIS_AGENT_NAMES: dict[Axis, str] = {
    Axis.CONVENIENCE: "MobilityAndShoppingAgent",
    Axis.HOUSING: "HousingCostAgent",
    Axis.FAMILY: "HealthcareAndFamilyAgent",
    Axis.SAFETY: "SafetyAndDisasterAgent",
    Axis.FUTURE: "CityFutureAgent",
}
